[custom]
enable_rule_generator=true
overwrite_original_rules=true
;Ruleset addresses, supports local files/URL
;Format: Group name,[type:]URL[,interval]
;        Group name,[]Rule
;where "type" supports the following value: surge, quanx, clash-domain, clash-ipcidr, clash-classic
;type defaults to surge if omitted

ruleset=XiaoMi,https://raw.githubusercontent.com/ciaoly/clash-custom-ruleset/refs/heads/main/XiaoMi.yaml
ruleset=Adblock,https://raw.githubusercontent.com/TG-Twilight/AWAvenue-Ads-Rule/main/Filters/AWAvenue-Ads-Rule-Clash.yaml
ruleset=Steam,https://raw.githubusercontent.com/ciaoly/clash-custom-ruleset/refs/heads/main/Steam.list
ruleset=OpenAI,https://raw.githubusercontent.com/ciaoly/clash-custom-ruleset/refs/heads/main/OpenAI.list
ruleset=Bilibili,https://raw.githubusercontent.com/ciaoly/clash-custom-ruleset/refs/heads/main/bilibili.list
ruleset=REJECT,rules/DivineEngine/Surge/Ruleset/Guard/Hijacking.list
ruleset=DIRECT,https://raw.githubusercontent.com/ciaoly/clash-custom-ruleset/refs/heads/main/ForceDirect.list
ruleset=Proxies,https://raw.githubusercontent.com/ciaoly/clash-custom-ruleset/refs/heads/main/ForceProxy.list
ruleset=Apple,rules/DivineEngine/Surge/Ruleset/Extra/Apple/Apple.list
ruleset=MicroSoft,https://raw.githubusercontent.com/ciaoly/clash-custom-ruleset/refs/heads/main/microsoft.list
ruleset=Telegram,rules/DivineEngine/Surge/Ruleset/Extra/Telegram/Telegram.list
ruleset=Netflix,https://raw.githubusercontent.com/ciaoly/clash-custom-ruleset/refs/heads/main/netflix.list
ruleset=Netease,https://raw.githubusercontent.com/ciaoly/clash-custom-ruleset/refs/heads/main/netease.list
ruleset=HKMTMedia,https://raw.githubusercontent.com/ciaoly/clash-custom-ruleset/refs/heads/main/HKMTMedia.list
ruleset=Proxies,rules/DivineEngine/Surge/Ruleset/StreamingMedia/Streaming.list
ruleset=Proxies,rules/DivineEngine/Surge/Ruleset/Global.list
ruleset=Proxies,https://raw.githubusercontent.com/ciaoly/clash-custom-ruleset/refs/heads/main/Proxies.list
ruleset=DIRECT,rules/LocalAreaNetwork.list
ruleset=DIRECT,rules/DivineEngine/Surge/Ruleset/Unbreak.list
# ruleset=Domestic,rules/DivineEngine/Surge/Ruleset/China.list
ruleset=Domestic,https://raw.githubusercontent.com/ciaoly/clash-custom-ruleset/refs/heads/main/ChinaIPs.list
ruleset=Domestic,https://raw.githubusercontent.com/ciaoly/clash-custom-ruleset/refs/heads/main/China.list
ruleset=Final,[]MATCH

;Generate Clash Proxy Group with the following patterns. Node filtering rule supports regular expression.
;Format: Group_Name`select`Rule_1`Rule_2`...
;        Group_Name`url-test|fallback|load-balance`Rule_1`Rule_2`...`test_url`interval[,timeout][,tolerance]
;Rule with "[]" prefix will be added directly.

custom_proxy_group=Proxies`select`[]🇭🇰 HK`[]🇸🇬 SG`[]🇯🇵 JP`[]🇺🇸 US`[]🇹🇼 TW`.*
custom_proxy_group=OpenAI`select`[]🇭🇰 HK`[]🇸🇬 SG`[]🇯🇵 JP`[]🇺🇸 US`[]🇹🇼 TW`.*
custom_proxy_group=Steam`select`[]Domestic`[]Proxies`[]🇭🇰 HK`[]🇸🇬 SG`[]🇯🇵 JP`[]🇺🇸 US`[]🇹🇼 TW`.*
custom_proxy_group=Apple`select`[]Domestic`[]DIRECT`[]Proxies
custom_proxy_group=MicroSoft`select`[]Domestic`[]DIRECT`[]Proxies
custom_proxy_group=Telegram`select`[]Proxies`[]🇭🇰 HK`[]🇸🇬 SG
custom_proxy_group=Bilibili`select`[]Domestic`[]Proxies`[]🇭🇰 HK`[]🇹🇼 TW`[]🇸🇬 SG
custom_proxy_group=Netflix`select`[]Proxies`[]🇭🇰 HK`[]🇸🇬 SG`[]🇺🇸 US
custom_proxy_group=Netease`select`[]Domestic`[]DIRECT`[]Proxies`Netease
custom_proxy_group=HKMTMedia`select`[]Domestic`[]DIRECT`[]Proxies`[]🇭🇰 HK`[]🇹🇼 TW
custom_proxy_group=Adblock`[]REJECT`[]DIRECT`[]Domestic
custom_proxy_group=Domestic`select`[]DIRECT
custom_proxy_group=XiaoMi`select`[]Domestic`[]DIRECT`[]Proxies
custom_proxy_group=Final`select`[]Proxies`[]Domestic`[]DIRECT
custom_proxy_group=🇭🇰 HK`select`香港
custom_proxy_group=🇸🇬 SG`select`新加坡
custom_proxy_group=🇹🇼 TW`select`台湾
custom_proxy_group=🇯🇵 JP`select`日本
custom_proxy_group=🇺🇸 US`select`美国

[userinfo]
; 从节点名中提取流量信息及显示的规则
; 匹配目标：剩余流量：148.3 GB
stream_rule=^剩余流量：(.*)$|left=$1

; 从节点名中提取时间信息的规则
; 匹配目标 1：套餐到期：2027-11-11
time_rule=^套餐到期：(\d+)-(\d+)-(\d+)$|$1:$2:$3:0:0:0

